travis:
  secure:
    BINSTAR_TOKEN: PN1M0wHAug+cJ4MgFn5sUAmjB1jJjenUwv0pAqMggsCpZ6Tnmp0/1KozjxNl7FPye1pRJaXRXkfC0vIIxrIX+LqzevofwxLBtonILRE9mq+jb0BKS6Pxe5pzxj7GGpQNskLP0s3IzmKliQh5S13Q/WlZE78Pco8up8aariHd9KLh5QP4No5AOoBVM2K77yAEq4fE6JN0zhdFK4Dqcv+Uh3NSXT1QpDACpT3WfE9TaPe1IWbkrB+2O3FcTG5tmvV8IuwfYaWrUtEjhycFcCK1kZ1vBg09UNi+SyeIu6JrY5P3v30PXOCNkvhk4pwoajo3qZXs05rn3xRxBIwGoCFMUoF64CT1GvHHRnZSM/p7L10/3+WuYbYI5AwAjJ3W0SBcNS0KYR8f5xgRW9w4HjoFhBKNimibMFBmbXYuIDNMCBzZKEEiMQ+obzzgPO9d4PSxbGoiBDP8BG0XG8vk0pAY2IXvcgwJLUiA3sq1jRy/ItMzrrpKBeNejm7i6L9c05bkHSA/WcFKxwAScTlleeP2fLdaAQunY4WmlmmX33MV3KJLZ4IH8l9UQS1vba+h270BtNdvWiOfYNE5IO56/zJKXPlkl9RR9tFG8F5AoLH2yD0+O+M+2RkZmzS2PRhX4x9zzorF4vAZcR7H2W4165f9zdcwHMiSIWy6vdmaxcfA/Y0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
